services:
  - type: web
    name: charm-bot
    env: node
    buildCommand: npm install
    startCommand: NODE_ENV=production node bot.js
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production 